defaults:
  -
    scope:
      path: ''

    values:
      layout: default

  -
    scope:
      path: ''
      type: posts

    values:
      layout: post

permalink: pretty

download_link: http://open-addresses-ltd.s3-website-eu-west-1.amazonaws.com/addresses.csv.torrent